// This file is autogenerated from scripts/src/generate-example
/* eslint-disable */
import React from 'react';
import Table from 'terra-table';
import IconOutlineIncentives from 'terra-consumer-icon/lib/icon/IconOutlineIncentives';
import IconOutlineFootsteps from 'terra-consumer-icon/lib/icon/IconOutlineFootsteps';
import IconOutlineRunning from 'terra-consumer-icon/lib/icon/IconOutlineRunning';
import IconOutlineDonutChart from 'terra-consumer-icon/lib/icon/IconOutlineDonutChart';
import IconOutlineAwardRibbon from 'terra-consumer-icon/lib/icon/IconOutlineAwardRibbon';
import IconOutlineLink from 'terra-consumer-icon/lib/icon/IconOutlineLink';
import IconOutlineCalendarDays from 'terra-consumer-icon/lib/icon/IconOutlineCalendarDays';
import IconOutlineVitalsCircle from 'terra-consumer-icon/lib/icon/IconOutlineVitalsCircle';
import IconOutlineWeightScale from 'terra-consumer-icon/lib/icon/IconOutlineWeightScale';
import IconOutlineNav from 'terra-consumer-icon/lib/icon/IconOutlineNav';
import IconOutlineCog from 'terra-consumer-icon/lib/icon/IconOutlineCog';
import IconOutlineQuestionMark from 'terra-consumer-icon/lib/icon/IconOutlineQuestionMark';
import IconChatBubble from 'terra-consumer-icon/lib/icon/IconChatBubble';
import IconOutlineUserEdit from 'terra-consumer-icon/lib/icon/IconOutlineUserEdit';
import IconOutlineUserLock from 'terra-consumer-icon/lib/icon/IconOutlineUserLock';
import IconDataSync from 'terra-consumer-icon/lib/icon/IconDataSync';
import IconOutlineChevronRight from 'terra-consumer-icon/lib/icon/IconOutlineChevronRight';
import IconOutlineChevronLeft from 'terra-consumer-icon/lib/icon/IconOutlineChevronLeft';
import IconOutlineChevronDown from 'terra-consumer-icon/lib/icon/IconOutlineChevronDown';
import IconOutlineChevronUp from 'terra-consumer-icon/lib/icon/IconOutlineChevronUp';
import IconOutlineAdd from 'terra-consumer-icon/lib/icon/IconOutlineAdd';
import IconOutlineCheck from 'terra-consumer-icon/lib/icon/IconOutlineCheck';
import IconOutlineCalendarSimple from 'terra-consumer-icon/lib/icon/IconOutlineCalendarSimple';
import IconOutlineInformation from 'terra-consumer-icon/lib/icon/IconOutlineInformation';
import IconOutlineSuccess from 'terra-consumer-icon/lib/icon/IconOutlineSuccess';
import IconOutlineWarning from 'terra-consumer-icon/lib/icon/IconOutlineWarning';
import IconOutlineError from 'terra-consumer-icon/lib/icon/IconOutlineError';
import IconOutlineFilter from 'terra-consumer-icon/lib/icon/IconOutlineFilter';
import IconOutlineLocationPin from 'terra-consumer-icon/lib/icon/IconOutlineLocationPin';
import IconOutlineFingerprint from 'terra-consumer-icon/lib/icon/IconOutlineFingerprint';
import IconOutlineEyeglasses from 'terra-consumer-icon/lib/icon/IconOutlineEyeglasses';
import IconOutlineHeartBeat from 'terra-consumer-icon/lib/icon/IconOutlineHeartBeat';
import IconOutlineNeedle from 'terra-consumer-icon/lib/icon/IconOutlineNeedle';
import IconOutlineApple from 'terra-consumer-icon/lib/icon/IconOutlineApple';
import IconOutlineRunningShoe from 'terra-consumer-icon/lib/icon/IconOutlineRunningShoe';
import IconOutlineMeditation from 'terra-consumer-icon/lib/icon/IconOutlineMeditation';
import IconOutlineLifesaver from 'terra-consumer-icon/lib/icon/IconOutlineLifesaver';
import IconOutlineCigarette from 'terra-consumer-icon/lib/icon/IconOutlineCigarette';
import IconOutlineMartini from 'terra-consumer-icon/lib/icon/IconOutlineMartini';
import IconOutlineGrowth from 'terra-consumer-icon/lib/icon/IconOutlineGrowth';
import IconOutlineProductivity from 'terra-consumer-icon/lib/icon/IconOutlineProductivity';
import IconOutlineUsersHouse from 'terra-consumer-icon/lib/icon/IconOutlineUsersHouse';
import IconOutlineCertificate from 'terra-consumer-icon/lib/icon/IconOutlineCertificate';
import IconOutlineSquareHeartRate from 'terra-consumer-icon/lib/icon/IconOutlineSquareHeartRate';
const IconAll = () => (
  <div>  <Table isStriped={false} >
    <Table.Header>
      <Table.HeaderCell content={'SVG'} key={'svg'} />
      <Table.HeaderCell content={'Concept'} key={'concept'} />
      <Table.HeaderCell content={'Code'} key={'code'} />
    </Table.Header>
    <Table.Rows>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineIncentives height='2em' width='2em' /></td>
        <td>outline-incentives</td>
        <td>
          import IconOutlineIncentives from 'terra-consumer-icon/lib/icon/IconOutlineIncentives';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineFootsteps height='2em' width='2em' /></td>
        <td>outline-footsteps</td>
        <td>
          import IconOutlineFootsteps from 'terra-consumer-icon/lib/icon/IconOutlineFootsteps';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineRunning height='2em' width='2em' /></td>
        <td>outline-running</td>
        <td>
          import IconOutlineRunning from 'terra-consumer-icon/lib/icon/IconOutlineRunning';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineDonutChart height='2em' width='2em' /></td>
        <td>outline-donut-chart</td>
        <td>
          import IconOutlineDonutChart from 'terra-consumer-icon/lib/icon/IconOutlineDonutChart';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineAwardRibbon height='2em' width='2em' /></td>
        <td>outline-award-ribbon</td>
        <td>
          import IconOutlineAwardRibbon from 'terra-consumer-icon/lib/icon/IconOutlineAwardRibbon';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineLink height='2em' width='2em' /></td>
        <td>outline-link</td>
        <td>
          import IconOutlineLink from 'terra-consumer-icon/lib/icon/IconOutlineLink';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineCalendarDays height='2em' width='2em' /></td>
        <td>outline-calendar-days</td>
        <td>
          import IconOutlineCalendarDays from 'terra-consumer-icon/lib/icon/IconOutlineCalendarDays';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineVitalsCircle height='2em' width='2em' /></td>
        <td>outline-vitals-circle</td>
        <td>
          import IconOutlineVitalsCircle from 'terra-consumer-icon/lib/icon/IconOutlineVitalsCircle';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineWeightScale height='2em' width='2em' /></td>
        <td>outline-weight-scale</td>
        <td>
          import IconOutlineWeightScale from 'terra-consumer-icon/lib/icon/IconOutlineWeightScale';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineNav height='2em' width='2em' /></td>
        <td>outline-nav</td>
        <td>
          import IconOutlineNav from 'terra-consumer-icon/lib/icon/IconOutlineNav';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineCog height='2em' width='2em' /></td>
        <td>outline-cog</td>
        <td>
          import IconOutlineCog from 'terra-consumer-icon/lib/icon/IconOutlineCog';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineQuestionMark height='2em' width='2em' /></td>
        <td>outline-question-mark</td>
        <td>
          import IconOutlineQuestionMark from 'terra-consumer-icon/lib/icon/IconOutlineQuestionMark';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconChatBubble height='2em' width='2em' /></td>
        <td>chat-bubble</td>
        <td>
          import IconChatBubble from 'terra-consumer-icon/lib/icon/IconChatBubble';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineUserEdit height='2em' width='2em' /></td>
        <td>outline-user-edit</td>
        <td>
          import IconOutlineUserEdit from 'terra-consumer-icon/lib/icon/IconOutlineUserEdit';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineUserLock height='2em' width='2em' /></td>
        <td>outline-user-lock</td>
        <td>
          import IconOutlineUserLock from 'terra-consumer-icon/lib/icon/IconOutlineUserLock';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconDataSync height='2em' width='2em' /></td>
        <td>data-sync</td>
        <td>
          import IconDataSync from 'terra-consumer-icon/lib/icon/IconDataSync';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineChevronRight height='2em' width='2em' /></td>
        <td>outline-chevron-right</td>
        <td>
          import IconOutlineChevronRight from 'terra-consumer-icon/lib/icon/IconOutlineChevronRight';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineChevronLeft height='2em' width='2em' /></td>
        <td>outline-chevron-left</td>
        <td>
          import IconOutlineChevronLeft from 'terra-consumer-icon/lib/icon/IconOutlineChevronLeft';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineChevronDown height='2em' width='2em' /></td>
        <td>outline-chevron-down</td>
        <td>
          import IconOutlineChevronDown from 'terra-consumer-icon/lib/icon/IconOutlineChevronDown';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineChevronUp height='2em' width='2em' /></td>
        <td>outline-chevron-up</td>
        <td>
          import IconOutlineChevronUp from 'terra-consumer-icon/lib/icon/IconOutlineChevronUp';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineAdd height='2em' width='2em' /></td>
        <td>outline-add</td>
        <td>
          import IconOutlineAdd from 'terra-consumer-icon/lib/icon/IconOutlineAdd';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineCheck height='2em' width='2em' /></td>
        <td>outline-check</td>
        <td>
          import IconOutlineCheck from 'terra-consumer-icon/lib/icon/IconOutlineCheck';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineCalendarSimple height='2em' width='2em' /></td>
        <td>outline-calendar-simple</td>
        <td>
          import IconOutlineCalendarSimple from 'terra-consumer-icon/lib/icon/IconOutlineCalendarSimple';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineInformation height='2em' width='2em' /></td>
        <td>outline-information</td>
        <td>
          import IconOutlineInformation from 'terra-consumer-icon/lib/icon/IconOutlineInformation';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineSuccess height='2em' width='2em' /></td>
        <td>outline-success</td>
        <td>
          import IconOutlineSuccess from 'terra-consumer-icon/lib/icon/IconOutlineSuccess';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineWarning height='2em' width='2em' /></td>
        <td>outline-warning</td>
        <td>
          import IconOutlineWarning from 'terra-consumer-icon/lib/icon/IconOutlineWarning';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineError height='2em' width='2em' /></td>
        <td>outline-error</td>
        <td>
          import IconOutlineError from 'terra-consumer-icon/lib/icon/IconOutlineError';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineFilter height='2em' width='2em' /></td>
        <td>outline-filter</td>
        <td>
          import IconOutlineFilter from 'terra-consumer-icon/lib/icon/IconOutlineFilter';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineLocationPin height='2em' width='2em' /></td>
        <td>outline-location-pin</td>
        <td>
          import IconOutlineLocationPin from 'terra-consumer-icon/lib/icon/IconOutlineLocationPin';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineFingerprint height='2em' width='2em' /></td>
        <td>outline-fingerprint</td>
        <td>
          import IconOutlineFingerprint from 'terra-consumer-icon/lib/icon/IconOutlineFingerprint';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineEyeglasses height='2em' width='2em' /></td>
        <td>outline-eyeglasses</td>
        <td>
          import IconOutlineEyeglasses from 'terra-consumer-icon/lib/icon/IconOutlineEyeglasses';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineHeartBeat height='2em' width='2em' /></td>
        <td>outline-heart-beat</td>
        <td>
          import IconOutlineHeartBeat from 'terra-consumer-icon/lib/icon/IconOutlineHeartBeat';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineNeedle height='2em' width='2em' /></td>
        <td>outline-needle</td>
        <td>
          import IconOutlineNeedle from 'terra-consumer-icon/lib/icon/IconOutlineNeedle';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineApple height='2em' width='2em' /></td>
        <td>outline-apple</td>
        <td>
          import IconOutlineApple from 'terra-consumer-icon/lib/icon/IconOutlineApple';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineRunningShoe height='2em' width='2em' /></td>
        <td>outline-running-shoe</td>
        <td>
          import IconOutlineRunningShoe from 'terra-consumer-icon/lib/icon/IconOutlineRunningShoe';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineMeditation height='2em' width='2em' /></td>
        <td>outline-meditation</td>
        <td>
          import IconOutlineMeditation from 'terra-consumer-icon/lib/icon/IconOutlineMeditation';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineLifesaver height='2em' width='2em' /></td>
        <td>outline-lifesaver</td>
        <td>
          import IconOutlineLifesaver from 'terra-consumer-icon/lib/icon/IconOutlineLifesaver';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineCigarette height='2em' width='2em' /></td>
        <td>outline-cigarette</td>
        <td>
          import IconOutlineCigarette from 'terra-consumer-icon/lib/icon/IconOutlineCigarette';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineMartini height='2em' width='2em' /></td>
        <td>outline-martini</td>
        <td>
          import IconOutlineMartini from 'terra-consumer-icon/lib/icon/IconOutlineMartini';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineGrowth height='2em' width='2em' /></td>
        <td>outline-growth</td>
        <td>
          import IconOutlineGrowth from 'terra-consumer-icon/lib/icon/IconOutlineGrowth';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineProductivity height='2em' width='2em' /></td>
        <td>outline-productivity</td>
        <td>
          import IconOutlineProductivity from 'terra-consumer-icon/lib/icon/IconOutlineProductivity';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineUsersHouse height='2em' width='2em' /></td>
        <td>outline-users-house</td>
        <td>
          import IconOutlineUsersHouse from 'terra-consumer-icon/lib/icon/IconOutlineUsersHouse';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineCertificate height='2em' width='2em' /></td>
        <td>outline-certificate</td>
        <td>
          import IconOutlineCertificate from 'terra-consumer-icon/lib/icon/IconOutlineCertificate';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconOutlineSquareHeartRate height='2em' width='2em' /></td>
        <td>outline-square-heart-rate</td>
        <td>
          import IconOutlineSquareHeartRate from 'terra-consumer-icon/lib/icon/IconOutlineSquareHeartRate';
        </td>
      </tr>
    </Table.Rows>
  </Table>
  </div>);

export default IconAll;
