// This file is autogenerated from scripts/src/generate-example
/* eslint-disable */
import React from 'react';
import Table from 'terra-table';
import IconColorIncentives from 'terra-consumer-icon/lib/icon/IconColorIncentives';
import IconColorFootsteps from 'terra-consumer-icon/lib/icon/IconColorFootsteps';
import IconColorRunning from 'terra-consumer-icon/lib/icon/IconColorRunning';
import IconColorAward49 from 'terra-consumer-icon/lib/icon/IconColorAward49';
import IconUiColor1CalendarGrid61 from 'terra-consumer-icon/lib/icon/IconUiColor1CalendarGrid61';
import IconColorWeightScale from 'terra-consumer-icon/lib/icon/IconColorWeightScale';
import IconColorPeakFlow from 'terra-consumer-icon/lib/icon/IconColorPeakFlow';
import IconColorHeartRate from 'terra-consumer-icon/lib/icon/IconColorHeartRate';
import IconColorBloodGlucose from 'terra-consumer-icon/lib/icon/IconColorBloodGlucose';
import IconColorBloodPressure from 'terra-consumer-icon/lib/icon/IconColorBloodPressure';
import IconColorPulseOximetry from 'terra-consumer-icon/lib/icon/IconColorPulseOximetry';
const IconAll = () => (
  <div>  <Table isStriped={false} >
    <Table.Header>
      <Table.HeaderCell content={'SVG'} key={'svg'} />
      <Table.HeaderCell content={'Concept'} key={'concept'} />
      <Table.HeaderCell content={'Code'} key={'code'} />
    </Table.Header>
    <Table.Rows>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconColorIncentives height='2em' width='2em' /></td>
        <td>color-incentives</td>
        <td>
          import IconColorIncentives from 'terra-consumer-icon/lib/icon/IconColorIncentives';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconColorFootsteps height='2em' width='2em' /></td>
        <td>color-footsteps</td>
        <td>
          import IconColorFootsteps from 'terra-consumer-icon/lib/icon/IconColorFootsteps';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconColorRunning height='2em' width='2em' /></td>
        <td>color-running</td>
        <td>
          import IconColorRunning from 'terra-consumer-icon/lib/icon/IconColorRunning';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconColorAward49 height='2em' width='2em' /></td>
        <td>color_award-49</td>
        <td>
          import IconColorAward49 from 'terra-consumer-icon/lib/icon/IconColorAward49';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconUiColor1CalendarGrid61 height='2em' width='2em' /></td>
        <td>ui-color-1_calendar-grid-61</td>
        <td>
          import IconUiColor1CalendarGrid61 from 'terra-consumer-icon/lib/icon/IconUiColor1CalendarGrid61';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconColorWeightScale height='2em' width='2em' /></td>
        <td>color-weight-scale</td>
        <td>
          import IconColorWeightScale from 'terra-consumer-icon/lib/icon/IconColorWeightScale';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconColorPeakFlow height='2em' width='2em' /></td>
        <td>color-peak-flow</td>
        <td>
          import IconColorPeakFlow from 'terra-consumer-icon/lib/icon/IconColorPeakFlow';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconColorHeartRate height='2em' width='2em' /></td>
        <td>color-heart-rate</td>
        <td>
          import IconColorHeartRate from 'terra-consumer-icon/lib/icon/IconColorHeartRate';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconColorBloodGlucose height='2em' width='2em' /></td>
        <td>color-blood-glucose</td>
        <td>
          import IconColorBloodGlucose from 'terra-consumer-icon/lib/icon/IconColorBloodGlucose';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconColorBloodPressure height='2em' width='2em' /></td>
        <td>color-blood-pressure</td>
        <td>
          import IconColorBloodPressure from 'terra-consumer-icon/lib/icon/IconColorBloodPressure';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconColorPulseOximetry height='2em' width='2em' /></td>
        <td>color-pulse-oximetry</td>
        <td>
          import IconColorPulseOximetry from 'terra-consumer-icon/lib/icon/IconColorPulseOximetry';
        </td>
      </tr>
    </Table.Rows>
  </Table>
  </div>);

export default IconAll;
