// This file is autogenerated from scripts/src/generate-example
/* eslint-disable */
import React from 'react';
import Table from 'terra-table';
import IconColorIncentives from 'ICON_TARGET_PATH/IconAbnormal';
import IconColorFootsteps from 'ICON_TARGET_PATH/IconAlert';

const IconCustom = () => (
  <div>  <Table isStriped={false} >
    <Table.Header>
      <Table.HeaderCell content={'SVG'} key={'svg'} />
      <Table.HeaderCell content={'Concept'} key={'concept'} />
      <Table.HeaderCell content={'Code'} key={'code'} />
    </Table.Header>
    <Table.Rows>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconColorIncentives height='2em' width='2em' /></td>
        <td>color-incentives</td>
        <td>
          import IconColorIncentives from 'terra-consumer-icon/lib/icon/IconColorIncentives';
        </td>
      </tr>
      <tr style={{ backgroundColor: '#EEEEEE' }}>
        <td><IconColorFootsteps height='2em' width='2em' /></td>
        <td>color-footsteps</td>
        <td>
          import IconColorFootsteps from 'terra-consumer-icon/lib/icon/IconColorFootsteps';
        </td>
      </tr>
    </Table.Rows>
  </Table>
  </div>);

export default IconCustom;
